server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    statusPageUrlPath: ${management.contextPath}/info
    healthCheckUrlPath: ${management.contextPath}/health
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaulZone:  http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0